#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  
  # viene eseguita per tutti i branch che non hanno una pipeline associata
  default:
      - step:
          name: Build and Test (CI)
          caches:
            - maven
          script:
            # CI: build e test
            - export CI=true
            - mvn -B verify --file mioProgetto/pom.xml
          after-script:  
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
          artifacts:
            - mioProgetto/target/**
  
      - step:
          name: Deploy su dockerhub (CD)
          script:
            # creo immagine docker pronta per essere pubblicata su dockerhub
            - docker image build -f mioProgetto/Dockerfile --tag lssndr96/progettoisa:0.1 mioProgetto
            # login su dockerhub
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push dell'immagine su dockerhub
            - docker push lssndr96/progettoisa:0.1
          services:
            - docker 

      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
